### ISSUE TITLE
This library breaks deployment with cloudflare

### ISSUE THREAD

**Issue by irg1008** [Alexandre-Fernandez/astro-i18n#85]
**Describe the bug**

**To Reproduce**
1. pnpm install
2. build project
3. See errors related to node APIs
4. You may remove all astro-i18n from the project
5. The project now builds correctly as it should

**Expected behavior**
We should be able to build astro project with cloudflare adapter

**Mandatory reproduction repository**
https://github.com/irg1008/ivanruiz

**Comment by irg1008** [comment]
I think this library has potential to be one of the main astro i18n packages if not the main one. You have managed 200+ stars without proper documentation or releases or even proper commits. I am willing to help out and submit PRs and test things but would be great to know if you plan to support this package before I translate every single string in my app with this currently broken package.

Again I love this approach so please please don't abandon this project

**Comment by irg1008** [comment]
I think would be "easy" to fix updating dependencies to use "node:*"

**Comment by irg1008** [comment]
```powershell
[vite-plugin-pwa:build] [plugin vite:resolve] Cannot bundle Node.js built-in "fs" imported from "node_modules\.pnpm\esbuild@0.20.2\node_modules\esbuild\lib\main.js". Consider disabling ssr.noExternal or remove the built-in dependency.
file: C:/Users/Ivan/Documents/Projects/Web/ivanruiz/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js
  Stack trace:
    at getRollupError (file:///C:/Users/Ivan/Documents/Projects/Web/ivanruiz/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/parseAst.js:376:41)
    at Object.error (file:///C:/Users/Ivan/Documents/Projects/Web/ivanruiz/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/node-entry.js:19378:20)
    at Object.handler (file:///C:/Users/Ivan/Documents/Projects/Web/ivanruiz/node_modules/.pnpm/vite@5.2.2_@types+node@20.11.30_lightningcss@1.24.1/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:67458:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveId (file:///C:/Users/Ivan/Documents/Projects/Web/ivanruiz/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/node-entry.js:18144:26)
 ELIFECYCLE  Command failed with exit code 1.
```

I have confirmed removing this library removes the error

**Comment by irg1008** [comment]
Breaks deplyment with deno deploy as well. Does this work with any SSR adapter at all?

**Comment by rodilo** [comment]
@irg1008 did you manage to make this work with cloudflare?

**Comment by irg1008** [comment]
No, ended up using netlify
