### ISSUE TITLE
[ERROR] Invalid URL

### ISSUE THREAD

**Issue by narduin** [Alexandre-Fernandez/astro-i18n#87]
**Describe the bug**

Versions:

-  astro@4.9.2
-  astro-i18n@2.2.4
-  node v18.20.3 & 20.13.1 tested

An error is happening as soon as I launch my astro project.

At first it was working insanely great, but at some point (and I don't know why) it started showing this error constantly.

```log
TypeError
An error occurred.

Invalid URL
src/index.js:12:30050

TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at set route [as route] (/i18n-bug/node_modules/astro-i18n/dist/src/index.js:12:30050)
    at /i18n-bug/node_modules/astro-i18n/dist/src/index.js:12:36680
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callMiddleware (file:///i18n-bug/node_modules/astro/dist/core/middleware/callMiddleware.js:21:10)
    at async RenderContext.render (file:///i18n-bug/node_modules/astro/dist/core/render-context.js:148:22)
    at async handleRoute (file:///i18n-bug/node_modules/astro/dist/vite-plugin-astro-server/route.js:209:18)
    at async run (file:///i18n-bug/node_modules/astro/dist/vite-plugin-astro-server/request.js:40:14)
    at async runWithErrorHandling (file:///i18n-bug/node_modules/astro/dist/vite-plugin-astro-server/controller.js:64:5)
    at async handleRequest (file:///i18n-bug/node_modules/astro/dist/vite-plugin-astro-server/request.js:34:3)
```

I didn't event import astroI18n or a translation function into the page.

**To Reproduce**

1. Create an astro project (latest is 4.9.2)
2. Add astro-i18n and config
3. Add an index page with a
4. Sync i18n and launch dev server
5. try to navigate/reload pages

**Expected behavior**
Website should show pages.

**Mandatory reproduction repository**
[Add a git repository to reproduce the bug.](https://github.com/narduin/i18n-astro-bug)

Thanks a lot!

**Comment by filipslezaklab** [comment]
Got the same issue, on setup it worked and after i18n:sync it broke with that error and never worked again, with this bug this otherwise great lib is unusable. Tried downgrading both astro and astro-i18n versions but did not help. Did not matter if there was only one language or multiple.

**Comment by Haxikowy** [comment]
@Alexandre-Fernandez Is it possible this will be fixed? I found out that it does work when you have created `404.astro` page and have `astro@4.15.8` at the most.

**Comment by filip-glowicki** [comment]
I have the same problem as @Haxikowy. I would be very grateful if you would give information on this matter :)

**Comment by ehrencrona** [comment]
This issue here seems to be that URL_PATTERN matches `/favicon.ico`, so `set route(route: string)` in `astro-i18n.class` will interpret that path as a URL and then try to parse it which causes this problem.

The workaround until this has been fixed in astro-i18n would be to simply add a favicon.ico to the public folder of your project.

**Comment by konstantinosbotonakis** [comment]
The issue still exists...

**Comment by albertosgr** [comment]
on my side, it was Chrome dev tools request. 
You can resolve it (workaround) by installing vite's plugin (https://github.com/ChromeDevTools/vite-plugin-devtools-json)
or handle in in your middleware before i18n.

in astro.config

```js
import { defineConfig } from 'astro/config';
import devtoolsJson from 'vite-plugin-devtools-json';

....

export default defineConfig({
  ...
  vite: {
     plugins: [
         devtoolsJson(),
     ],
  }
...
})
```

**Comment by uigywnkiub** [comment]
> on my side, it was Chrome dev tools request. You can resolve it (workaround) by installing vite's plugin (https://github.com/ChromeDevTools/vite-plugin-devtools-json) or handle in in your middleware before i18n.
> 
> in astro.config
> 
> import { defineConfig } from 'astro/config';
> import devtoolsJson from 'vite-plugin-devtools-json';
> 
> ....
> 
> export default defineConfig({
>   ...
>   vite: {
>      plugins: [
>          devtoolsJson(),
>      ],
>   }
> ...
> })

Currently not work.
